// src/components/admin/ReportsAndAnalytics.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";
import "./admincss/ReportsAndAnalytics.css";

const ADMIN_API = `${import.meta.env.VITE_API_URL}/admin`;

function ReportsAndAnalytics() {
  const [stats, setStats] = useState({
    donorCount: 0,
    creatorCount: 0,
    campaignCount: 0,
    totalDonations: 0,
  });
  const [domainData, setDomainData] = useState([]);
  const [campaignData, setCampaignData] = useState([]);
  const [loading, setLoading] = useState(true);

  const COLORS = ["#0088FE", "#00C49F", "#FFBB28", "#FF8042", "#AA336A"];

  useEffect(() => {
    (async () => {
      try {
        const [
          donorRes,
          creatorRes,
          campaignCountRes,
          totalDonRes,
          campaignsRes,
        ] = await Promise.all([
          axios.get(`${ADMIN_API}/donorcount`),
          axios.get(`${ADMIN_API}/creatorcount`),
          axios.get(`${ADMIN_API}/campaigncount`),
          axios.get(`${ADMIN_API}/donationsummary`),
          axios.get(`${ADMIN_API}/allcampaigns`),
        ]);

        setStats({
          donorCount: donorRes.data || 0,
          creatorCount: creatorRes.data || 0,
          campaignCount: campaignCountRes.data || 0,
          totalDonations: totalDonRes.data || 0,
        });

        const campaigns = campaignsRes.data || [];

        const domainMap = {};
        const campaignMap = {};

        campaigns.forEach((c) => {
          const category = c.category || "Other";
          const amount = c.collectedAmount || 0;

          domainMap[category] = (domainMap[category] || 0) + amount;

          const title = c.title || `Campaign ${c.id}`;
          campaignMap[title] = (campaignMap[title] || 0) + amount;
        });

        setDomainData(
          Object.keys(domainMap).map((name) => ({
            name,
            value: domainMap[name],
          }))
        );

        setCampaignData(
          Object.keys(campaignMap).map((name) => ({
            name,
            amount: campaignMap[name],
          }))
        );
      } catch (err) {
        console.error("Error loading analytics:", err);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  if (loading) {
    return (
      <div className="reports-container">
        <div className="reports-loading">Loading analytics...</div>
      </div>
    );
  }

  return (
    <div className="reports-container">
      <div className="reports-header">
        <div>
          <h1>Reports & Analytics</h1>
          <p>Overview of users and money generated on each domain</p>
        </div>
      </div>

      <div className="report-cards">
        <div className="report-card">
          <div className="report-label">Total Donations</div>
          <div className="report-value">₹{stats.totalDonations}</div>
        </div>
        <div className="report-card">
          <div className="report-label">Total Donors</div>
          <div className="report-value">{stats.donorCount}</div>
        </div>
        <div className="report-card">
          <div className="report-label">Total Creators</div>
          <div className="report-value">{stats.creatorCount}</div>
        </div>
        <div className="report-card">
          <div className="report-label">Total Campaigns</div>
          <div className="report-value">{stats.campaignCount}</div>
        </div>
      </div>

      <div className="charts-container">
        <div className="chart-card">
          <h3>Money Generated by Campaign</h3>
          {campaignData.length > 0 ? (
            <ResponsiveContainer width="100%" height={320}>
              <BarChart
                data={campaignData}
                margin={{ top: 20, right: 20, left: 0, bottom: 40 }}
              >
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis
                  dataKey="name"
                  tick={{ fontSize: 11 }}
                  interval={0}
                  angle={-25}
                  textAnchor="end"
                />
                <YAxis />
                <Tooltip />
                <Bar dataKey="amount" fill="#0088FE" />
              </BarChart>
            </ResponsiveContainer>
          ) : (
            <p>No campaign data.</p>
          )}
        </div>

        <div className="chart-card">
          <h3>Money Generated by Domain</h3>
          {domainData.length > 0 ? (
            <ResponsiveContainer width="100%" height={320}>
              <PieChart>
                <Pie
                  data={domainData}
                  dataKey="value"
                  nameKey="name"
                  cx="50%"
                  cy="50%"
                  outerRadius={110}
                  label
                >
                  {domainData.map((entry, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={COLORS[index % COLORS.length]}
                    />
                  ))}
                </Pie>
                <Legend />
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          ) : (
            <p>No domain data.</p>
          )}
        </div>
      </div>
    </div>
  );
}

export default ReportsAndAnalytics;
